### ISSUE TITLE
发送数据失败

### ISSUE THREAD

**Issue by lzx9112** [zhanguangao/react-native-ble-manager-demo#1]
JS端传入的是String，BleManager write方法中第四个参数为ReadableArray因此会报错。
修改为String后再转成byte[]不报错但是几乎不能发送成功，大概5%的概率发送成功，其余case会在JS端alert发送失败。
求解答！我的微信为：442872082，谢谢🙏

**Comment by zhanguangao** [comment]
@lzx9112 你安装的是我fork后修改后的分支吗？如果是的话应该不会有这个问题

**Comment by lzx9112** [comment]
@zhanguangao 非常感谢🙏，确实装的是innoveit原版本，对比了代码后加入了修改，现在已经可以成功发送数据。

**Comment by lzx9112** [comment]
发送数据时需要与蓝牙硬件人员沟通好characteristic id，我之前发错了id导致APP端发送成功但是蓝牙段一直收不到，个人经验贴出来供需要的人做参考。同时 @zhanguangao strToHexByteArray方法在string长度为基数时报错，望修正。

**Comment by zhanguangao** [comment]
@lzx9112 谢谢提醒，所有的数据转换都是以偶数为基础的，好多地方都没检验

**Comment by qianlanse** [comment]
@zhanguangao 我现在用的react-native-ble-manager版本是^6.5.4，按照你源码修改后（我看好像只修改了BleManager文件里面write，writeWithoutResponse两个方法是吗） 发送数据是报Attempt to invoke interface method 'int com.facebook.react.bridge.ReadableArray.size()' on a null object reference
