### ISSUE TITLE
获取我的蓝牙MAC地址

### ISSUE THREAD

**Issue by 1459726992** [zhanguangao/react-native-ble-manager-demo#2]
I need to send my bluetooth MAC address to the server to verify my legitimacy, but I don't know how to get it

**Comment by zhanguangao** [comment]
是手机的Mac地址还是扫描其他设备的Mac地址？@1459726992

**Comment by 1459726992** [comment]
自己的安卓平板蓝牙地址， react-native-ble-manager没有找到方法
我现在在使用你推荐的react native ble plx 也只能得到扫描的蓝牙设备Mac地址 ，还没找到方法得到自己的
@zhanguangao

**Comment by zhanguangao** [comment]
你的方式错了，获取本机的蓝牙地址，你可以使用react-native-device-info的getMACAddress()方法@1459726992

**Comment by 1459726992** [comment]
谢谢你帮助我解决了这个问题
@zhanguangao
