### ISSUE TITLE
 init the module fail

### ISSUE THREAD

**Issue by qujunda** [zhanguangao/react-native-ble-manager-demo#23]
I use Expo for development. When I initialize Bluetooth, there are problems with “Init the module fail" and "TypeError: null is not an object (evaluating 'bleManager.checkState')". What should I do to solve this issue? And there is no Android directory in my project, so the permissions cannot be modified

**Comment by sunnleung** [comment]
I meet the same problem.Have you fixed it?

**Comment by zhanguangao** [comment]
I didn't test it in Expo. I think you can upgrade React Native and react-native-ble-manager version.

**Comment by sunnleung** [comment]
我是在xcode上搭建的项目，版本是reactnative0.67.4 和react-native-ble-manager8.0.4。
```
import BleManager from 'react-native-ble-manager'
...
BleManager.start({showAlert: false}).then(() => {
  console.log('init successful')
}).catch(error => {
  console.error(error)
})
```
无论真机测试还是模拟器，在metro上都报TypeError: null is not an object (evaluating 'bleManager.start')".我真机系统是ios15.4。
```
import BleManager from 'react-native-ble-manager'
import {NativeModules, NativeEventEmitter} from 'react-native'
...
const BleManagerModule = NativeModules.BleManager
console.log(BleManagerModule)
const BleManagerEmitter = new NativeEventEmitter(BleManagerModule)
```

在metro上显示"BleManagerModule" is "null"。ERROR: Invariant Violation: 'new NativeEventEmitter()' require a non-null argument。

**Comment by zhanguangao** [comment]
```
import BleManager from 'react-native-ble-manager'
...
BleManager.start({showAlert: false}).then(() => {
  console.log('init successful')
}).catch(error => {
  console.error(error)
})
```
将这里的BleManager改成React.NativeModules.BleManager试一下
最新版本的使用有变化，请参考https://github.com/innoveit/react-native-ble-manager/blob/master/BleManager.js

**Comment by sunnleung** [comment]
```
var bleManager = React.NativeModules.BleManager;
```
还是会报错
```
ERROR TypeError: undefined is not an object (ovaluating
'react.default. Native
Modules.BleManager!)
ERROR Invariant Violation: Module AppRegistry is not a registered callable mod
ule (calling runApplication). A frequent cause of the error is that the applicat
ion entry file path is incorrect.
This can also happen when the J bundle is corrupt or there is an carly in
itialization error when loading React Native.
```

**Comment by zhanguangao** [comment]
我这边暂时没时间去调试这个demo，建议你用官方的例子：https://github.com/innoveit/react-native-ble-manager/blob/master/example/App.js
