### ISSUE TITLE
請問版本搭配

### ISSUE THREAD

**Issue by alvinhuu** [zhanguangao/react-native-ble-manager-demo#24]
您好
  請問搭配的 Node.js, expo version 是什麼呢?
  因為用最新的無法執行   畫面一片白

**Comment by zhanguangao** [comment]
@alvinhuu 我之前没有试过在expo里运行，如果你要测试蓝牙功能的话也只能在真机里运行

**Comment by alvinhuu** [comment]
不好意思  如果我要在我的 iphone 上跑這隻demo
完整程序是不是可以展示一下... 我改用
npm install
npm start

但在 npm install 就會出現許多 error 是有關   react 版本, 如果是要相對應的版本是不是可以列一下您使用的版本?  thanks a lot

-------------------- Error message ----------------
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: BleManagerDemo@1.22.17
npm ERR! Found: react@16.9.0
npm ERR! node_modules/react
npm ERR!   react@"16.9.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-native@0.66.4
npm ERR! node_modules/react-native
npm ERR!   react-native@"^0.66.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
