### ISSUE TITLE
android  name  is  null 

### ISSUE THREAD

**Issue by tianweicc** [zhanguangao/react-native-ble-manager-demo#3]
android  name  is  null

**Comment by zhanguangao** [comment]
@zhanguangao yes, some devices don't have a name

**Comment by tianweicc** [comment]
@zhanguangao all name is null

**Comment by tianweicc** [comment]
@zhanguangao 老哥 还有问题  能不能加个qq  方便问几个小问题 感谢了

**Comment by tianweicc** [comment]
648338679

**Comment by zhanguangao** [comment]
@tianweicc 190525238
