### ISSUE TITLE
Question how to use better

### ISSUE THREAD

**Issue by keyz23** [zhanguangao/react-native-ble-manager-demo#4]
Hi, I tried his code (really interesting compliments) and I found some things that made me ask two questions.
1) Why do you sometimes lose the bluetooth connection? I connect to a device and after 5 seconds it disconnects.
2) It is by chance possible to make sure that once connected to a device it is possible to retrieve data from Read without having to click on the button (the 0000 + uuid + .... button)
Thanks and congratulations for your work.

**Comment by zhanguangao** [comment]
@keyz23 I am sorry you have some problems with this demo.
1.Frequent disconnection may be incompatible with your bluetooth. Why not try [react-native-ble-plx](https://github.com/Polidea/react-native-ble-plx), I also write a [demo](https://github.com/zhanguangao/react-native-ble-plx-demo).
2.It is a demo, I don't know what someone want to get, so I add buttons for every characteristicUUID.Read only can get the Fixed data form the bluetooth. If you want to get response data when you write, you should add 'BleManagerDidUpdateValueForCharacteristic' listener to monitor.

**Comment by keyz23** [comment]
Ok now i have another question for your demo :) 
What about the Notification System? I'm trying your demo (you have done a very good work) and if I click on the notification i received only an Alert: "Success". How can i receive the information? Thank you.

**Comment by zhanguangao** [comment]
Only if you open the notifacation successful, and add the "BleManagerDidUpdateState" listener, you can monitor the BLE change state (response data).  The state changes based on what you write.
